language: node_js

node_js: 'stable' # or another

cache: npm

directories:
  - ./sneakers-shop/node_modules

before_script:
  - npm install --prefix sneakers-shop

script:
  - npm run test --prefix sneakers-shop
