language: node_js

node_js: 'stable' # or another

cache: npm

directories:
  - node_modules

before_script:
  - npm install --prefix /sneakers-store

script:
  - npm run test --prefix /sneakers-store
