export const PRODUCTS = 'PRODUCTS';

export const PRODUCT = 'PRODUCT';

export const BAG = 'BAG';

export const REMOVE = 'REMOVE';

export const ADD_FAVORITES = 'ADD_FAVORITES';

export const REMOVE_FAVORITES = 'REMOVE_FAVORITES';

export const FAVORITES_PRODUCT = 'FAVORITES_PRODUCT';

export const ADD_CATEGORY = 'ADD_CATEGORY';

export const REMOVE_CATEGORY = 'REMOVE_CATEGORY';

export const SEARCH_PRODUCTS = 'SEARCH_PRODUCTS';

export const POPULAR_PRODUCT = 'POPULAR_PRODUCT';

export const ALL_PRODUCTS = 'ALL_PRODUCTS';

export const ADD_PRICE_CATEGORY = 'ADD_PRICE_CATEGORY';

export const ADD_BRAND_CATEGORY = 'ADD_BRAND_CATEGORY';

export const REMOVE_BRAND_CATEGORY = 'REMOVE_BRAND_CATEGORY';

export const ADD_STATUS_PRICE_CATEGORY = 'ADD_STATUS_PRICE_CATEGORY';

export const GET_MEN_PRODUCTS = 'GET_MEN_PRODUCTS';

export const GET_WOMEN_PRODUCTS = 'GET_WOMEN_PRODUCTS';

export const GET_KIDS_PRODUCTS = 'GET_KIDS_PRODUCTS';

export const GET_CONVERSE_PRODUCTS = 'GET_CONVERSE_PRODUCTS';

export const GET_JORDAN_PRODUCTS = 'GET_JORDAN_PRODUCTS';
